server:
  port: 9090
spring:
  # set name application
  application:
    name: server
  # setup database connection
  datasource:
    url: jdbc:mysql://localhost:3306/serverappk2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  # setup hibernate JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        
    security:
       user:
         name: user
         password: user
